#!/usr/bin/env bash
set -euET -o pipefail

script_name=$(basename "$0")
script_dir=$(dirname "$0")

################################################################################
# CLI Parameters
################################################################################
cycle_max=
SKIP_BUY_LADDER=false
PREVIEW_ONLY=false
REQUIRE_PREVIEW=false
APPROVE_PREVIEW=false
profile_json=
detect_from_image=
expected_bulk_mode=
layout_profile=

################################################################################
# default values
################################################################################
mouse_click=${script_dir}/macos_mouse_click.py
detect_script=${script_dir}/cookie_clicker_detect_coords.py
preview_script=${script_dir}/cookie_clicker_preview_plan.py
default_profile_json=${script_dir}/config/cookie_clicker_profile.defaults.json

################################################################################
# show command usage
################################################################################
function usage {
    message=${1:-}
    if [ ! -z "${message}" ]; then
        echo "Message: ${message}"
    fi
    cat <<EOF
Usage: ${script_name} [-h] [-c <count>] [-S] [-P <profile_json>] [-D <image.png>] [-N] [-R] [-A] [-B <x1|x10|x100>] [-L <layout>]

Operator loop: repeatedly runs a fixed buy ladder then a long cookie burst
via macos_mouse_click.py (see osx/README.md). When -P is provided, coordinates
come from that profile JSON. Omit -c to run until stopped.

Options
  -h            : Display this help message.
  -c <count>    : Run exactly this many cycles, then exit. Example: -c 1 is
                 one cycle; -c 10 runs ten. Each cycle is real automation
                 (clicks), not a dry run.
  -S            : Skip the buy ladder; only the long cookie burst (-n 3000)
                 runs each cycle. Combine with -c (e.g. -S -c 5).
  -P <file>     : Coordinate profile JSON generated by cookie_clicker_detect_coords.py.
  -D <image>    : Run coordinate detection from this screenshot before preview/run
                 (requires -P output path).
  -N            : Preview only. Build preview artifacts and exit without clicks.
  -R            : Require matching preview manifest before clicks.
  -A            : Auto-approve preview prompt (non-interactive automation).
  -B <mode>     : Expected bulk mode metadata (x1|x10|x100) for operator checks.
  -L <layout>   : Layout profile label metadata (e.g. desktop-max).

Example:
  ${script_name} -c 1
  ${script_name} -c 10
  ${script_name} -S -c 1
  ${script_name} -P osx/config/cookie_clicker_profile.sample.json -N
  ${script_name} -P /tmp/cookie-profile.json -D docs/osx/screenshots/cookie-clicker/Screenshot_2026-04-25_at_8.28.45_PM.png -N
  ${script_name} -P /tmp/cookie-profile.json -R -A -c 1
  ${script_name} -S
  ${script_name}
EOF
}

################################################################################
# get command line options
################################################################################
while getopts ":hc:SP:D:RA:B:L:N" opt; do
    case ${opt} in
        h)
            usage
            exit 0
            ;;
        c)
            cycle_max=${OPTARG}
            ;;
        S)
            SKIP_BUY_LADDER=true
            ;;
        P)
            profile_json=${OPTARG}
            ;;
        D)
            detect_from_image=${OPTARG}
            ;;
        R)
            REQUIRE_PREVIEW=true
            ;;
        A)
            APPROVE_PREVIEW=true
            ;;
        B)
            expected_bulk_mode=${OPTARG}
            ;;
        L)
            layout_profile=${OPTARG}
            ;;
        N)
            PREVIEW_ONLY=true
            ;;
        \?)
            usage "Invalid option: -${OPTARG}"
            exit 1
            ;;
        :)
            usage "Option -${OPTARG} requires an argument."
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ ! -f "${mouse_click}" ]; then
    usage "Clicker not found: ${mouse_click}"
    exit 1
fi

if [ ! -z "${cycle_max}" ]; then
    if ! [[ "${cycle_max}" =~ ^[1-9][0-9]*$ ]]; then
        usage "Invalid -c value: must be a positive integer (e.g. 1 or 10)."
        exit 1
    fi
fi

if [ ! -z "${expected_bulk_mode}" ]; then
    case "${expected_bulk_mode}" in
        x1|x10|x100) ;;
        *)
            usage "Invalid -B value. Use x1, x10, or x100."
            exit 1
            ;;
    esac
fi

if [ ! -z "${detect_from_image}" ] && [ -z "${profile_json}" ]; then
    usage "-D requires -P so detector output path is explicit."
    exit 1
fi

if [ ! -z "${profile_json}" ] && [ ! -f "${preview_script}" ]; then
    usage "Preview helper not found: ${preview_script}"
    exit 1
fi

if [ ! -z "${detect_from_image}" ] && [ ! -f "${detect_script}" ]; then
    usage "Detector helper not found: ${detect_script}"
    exit 1
fi

################################################################################
# functions
################################################################################
function click_target {
    label=${1}
    target_x=${2}
    target_y=${3}
    target_n=${4}
    echo "${label}"
    "${mouse_click}" -d 0 -x "${target_x}" -y "${target_y}" -n "${target_n}" -Y
}

function detect_profile_from_image {
    if [ -z "${detect_from_image}" ]; then
        return
    fi
    if [ ! -f "${detect_from_image}" ]; then
        usage "Detect image not found: ${detect_from_image}"
        exit 1
    fi
    python3 "${detect_script}" --input "${detect_from_image}" --output "${profile_json}" --profile auto >/dev/null
}

function load_profile_coordinates {
    coord_profile=${profile_json}
    if [ -z "${coord_profile}" ]; then
        coord_profile="${default_profile_json}"
    fi
    if [ ! -f "${coord_profile}" ]; then
        usage "Profile JSON not found: ${coord_profile}"
        exit 1
    fi

    eval "$(
        python3 - "${coord_profile}" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

rows = {row["name"]: row for row in data.get("ladder_rows", [])}
order = [
    "time_machine",
    "portal",
    "alchemy_lab",
    "shipment",
    "wizard_tower",
    "temple",
    "bank",
    "factory",
    "mine",
    "farm",
    "grandma",
    "cursor",
]

cookie = data.get("cookie") or {}
if "x" not in cookie or "y" not in cookie:
    print("profile JSON missing cookie.x or cookie.y", file=sys.stderr)
    sys.exit(1)

defaults = data.get("preview_defaults") or {}
print(f'COOKIE_X={float(cookie["x"])}')
print(f'COOKIE_Y={float(cookie["y"])}')
print(f'COOKIE_CLICK_COUNT={int(defaults.get("cookie_click_count", 3000))}')
print(f'LADDER_CLICK_COUNT={int(defaults.get("ladder_click_count", 5))}')
print(f'CYCLE_SLEEP_SECONDS={float(defaults.get("cycle_sleep_seconds", 30))}')

for key in order:
    row = rows.get(key)
    if not row:
        print(f"profile JSON missing ladder_rows entry: {key!r}", file=sys.stderr)
        sys.exit(1)
    ux = key.upper()
    print(f'{ux}_X={float(row["x"])}')
    print(f'{ux}_Y={float(row["y"])}')
PY
    )"
}

function preview_paths {
    preview_manifest=${profile_json%.json}.preview-manifest.json
    preview_image=${profile_json%.json}.preview.png
}

function render_preview_artifacts {
    if [ -z "${profile_json}" ]; then
        return
    fi
    preview_paths
    preview_args=()
    if [ "${SKIP_BUY_LADDER}" == true ]; then
        preview_args+=(--skip-ladder)
    fi
    python3 "${preview_script}" \
        --profile "${profile_json}" \
        --image-out "${preview_image}" \
        --manifest-out "${preview_manifest}" \
        --cookie-clicks "${COOKIE_CLICK_COUNT}" \
        --ladder-clicks "${LADDER_CLICK_COUNT}" \
        "${preview_args[@]}" >/dev/null
}

function verify_preview_manifest {
    if [ "${REQUIRE_PREVIEW}" == false ]; then
        return
    fi
    preview_paths
    if [ ! -f "${preview_manifest}" ]; then
        usage "Required preview manifest missing: ${preview_manifest}"
        exit 1
    fi
    python3 - "${profile_json}" "${preview_manifest}" "${SKIP_BUY_LADDER}" "${COOKIE_CLICK_COUNT}" "${LADDER_CLICK_COUNT}" <<'PY'
import hashlib
import json
import sys
profile_path, manifest_path, skip_ladder, cookie_clicks, ladder_clicks = sys.argv[1:]
with open(profile_path, "rb") as f:
    profile_hash = hashlib.sha256(f.read()).hexdigest()
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = json.load(f)
options = {
    "skip_ladder": skip_ladder.lower() == "true",
    "cookie_clicks": int(cookie_clicks),
    "ladder_clicks": int(ladder_clicks),
}
options_hash = hashlib.sha256(
    json.dumps(options, sort_keys=True).encode("utf-8")
).hexdigest()
if manifest.get("profile_hash") != profile_hash:
    raise SystemExit("profile hash mismatch")
if manifest.get("options_hash") != options_hash:
    raise SystemExit("options hash mismatch")
PY
}

function confirm_preview_before_clicks {
    if [ -z "${profile_json}" ]; then
        return
    fi
    if [ "${APPROVE_PREVIEW}" == true ]; then
        return
    fi
    preview_paths
    echo "Preview artifact: ${preview_image}"
    echo "Manifest: ${preview_manifest}"
    read -r -p "Proceed with real clicks using this preview? [y/N] " answer
    case "${answer}" in
        y|Y|yes|YES) ;;
        *)
            echo "Cancelled. No clicks executed."
            exit 1
            ;;
    esac
}

function run_buy_ladder {
    click_target "buy time machine" "${TIME_MACHINE_X}" "${TIME_MACHINE_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy portal" "${PORTAL_X}" "${PORTAL_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy alchemy lab" "${ALCHEMY_LAB_X}" "${ALCHEMY_LAB_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy shipment" "${SHIPMENT_X}" "${SHIPMENT_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy wizard tower" "${WIZARD_TOWER_X}" "${WIZARD_TOWER_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy temple" "${TEMPLE_X}" "${TEMPLE_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy bank" "${BANK_X}" "${BANK_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy factory" "${FACTORY_X}" "${FACTORY_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy mine" "${MINE_X}" "${MINE_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy farm" "${FARM_X}" "${FARM_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy grandma" "${GRANDMA_X}" "${GRANDMA_Y}" "${LADDER_CLICK_COUNT}"
    click_target "buy cursor" "${CURSOR_X}" "${CURSOR_Y}" "${LADDER_CLICK_COUNT}"
}

function run_once {
    date
    # uncomment export lines for debug output
    export MACOS_MOUSE_CLICK_DEBUG_TUI=yes
    export MACOS_MOUSE_CLICK_DEBUG_TUI_LOG=debug.json

    if [ "${SKIP_BUY_LADDER}" == false ]; then
        run_buy_ladder
    fi

    click_target "click the cookie" "${COOKIE_X}" "${COOKIE_Y}" "${COOKIE_CLICK_COUNT}"
    date
}

################################################################################
# main script logic
################################################################################
if [ ! -z "${layout_profile}" ]; then
    echo "layout profile metadata: ${layout_profile}"
fi
if [ ! -z "${expected_bulk_mode}" ]; then
    echo "expected bulk mode metadata: ${expected_bulk_mode}"
fi

detect_profile_from_image
load_profile_coordinates
render_preview_artifacts
verify_preview_manifest

if [ "${PREVIEW_ONLY}" == true ]; then
    echo "Preview-only mode complete. No clicks were sent."
    exit 0
fi

confirm_preview_before_clicks

cycle_done=0
while true; do
    run_once
    cycle_done=$((cycle_done + 1))
    if [ ! -z "${cycle_max}" ] && [ "${cycle_done}" -ge "${cycle_max}" ]; then
        break
    fi
    sleep "${CYCLE_SLEEP_SECONDS}"
done
